services:
  backend:
    build:
      context: ./backend
    ports:
      - "8085:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/employee_management
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/employee_management
    


  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employee_management
    ports:
      - "3306:3306"
    

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    
